config/routes.rb
Rails.application.routes.draw do
  resources :co_workings

  resources :fundings

  devise_for :users
  resources :product_of_the_weeks

  get 'page/Startseite'

  get 'page/StartUps'

  get 'page/Funding'

  get 'page/Impressum'

  get 'page/Datenschutz'

  root to: "page#Startseite"

end

app/models/co_working.rb
class CoWorking < ActiveRecord::Base
end

app/models/funding.rb
class Funding < ActiveRecord::Base
end

app/models/product_of_the_week.rb
class ProductOfTheWeek < ActiveRecord::Base
	has_attached_file 	:photo, 
						:styles => {:small => "150x150> "},
						:url 	=> "/assets/ProductOfTheWeek/:id/:style/:basename.:extension",
						:path 	=> ":rails_root/public/assets/ProductOfTheWeek/:id/:style//:basename.:extension"

	validates_attachment :photo
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable



	# if Rails.env.production?
	# 	devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
	# else
	# 	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/co_workings_controller.rb
class CoWorkingsController < ApplicationController
  before_action :set_co_working, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  respond_to :html

  def index
    @co_workings = CoWorking.all
    respond_with(@co_workings)
  end

  def show
    respond_with(@co_working)
  end

  def new
    @co_working = CoWorking.new
    respond_with(@co_working)
  end

  def edit
  end

  def create
    @co_working = CoWorking.new(co_working_params)
    @co_working.save
    respond_with(@co_working)
  end

  def update
    @co_working.update(co_working_params)
    respond_with(@co_working)
  end

  def destroy
    @co_working.destroy
    respond_with(@co_working)
  end

  private
    def set_co_working
      @co_working = CoWorking.find(params[:id])
    end

    def co_working_params
      params.require(:co_working).permit(:name, :address, :url, :description, :picture)
    end
end

app/controllers/fundings_controller.rb
class FundingsController < ApplicationController
  before_action :set_funding, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  respond_to :html

  def index
    @fundings = Funding.all
    respond_with(@fundings)
  end

  def show
    respond_with(@funding)
  end

  def new
    @funding = Funding.new
    respond_with(@funding)
  end

  def edit
  end

  def create
    @funding = Funding.new(funding_params)
    @funding.save
    respond_with(@funding)
  end

  def update
    @funding.update(funding_params)
    respond_with(@funding)
  end

  def destroy
    @funding.destroy
    respond_with(@funding)
  end

  private
    def set_funding
      @funding = Funding.find(params[:id])
    end

    def funding_params
      params.require(:funding).permit(:name, :adress, :focus, :url, :art, :description, :thumbnail)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def Startseite
  end

  def StartUps
  end

  def Funding

    # require 'net/http'
    #
    # url = URI.parse('http://www.reddit.com/search.json?q=borussiadortmund')
    # req = Net::HTTP::Get.new(url.to_s)
    # @res = Net::HTTP.start(url.host, url.port) {|http|
    #   http.request(req)
    # }

  end

  def Impressum
  end

  def Datenschutz
  end


end

app/controllers/product_of_the_weeks_controller.rb
class ProductOfTheWeeksController < ApplicationController
  before_action :set_product_of_the_week, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  # GET /product_of_the_weeks
  # GET /product_of_the_weeks.json
  def index
    @product_of_the_weeks = ProductOfTheWeek.all
  end

  # GET /product_of_the_weeks/1
  # GET /product_of_the_weeks/1.json
  def show
  end

  # GET /product_of_the_weeks/new
  def new
    @product_of_the_week = ProductOfTheWeek.new
  end

  # GET /product_of_the_weeks/1/edit
  def edit
  end

  # POST /product_of_the_weeks
  # POST /product_of_the_weeks.json
  def create
    @product_of_the_week = ProductOfTheWeek.new(product_of_the_week_params)

    respond_to do |format|
      if @product_of_the_week.save
        format.html { redirect_to @product_of_the_week, notice: 'Product of the week was successfully created.' }
        format.json { render :show, status: :created, location: @product_of_the_week }
      else
        format.html { render :new }
        format.json { render json: @product_of_the_week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_of_the_weeks/1
  # PATCH/PUT /product_of_the_weeks/1.json
  def update
    respond_to do |format|
      if @product_of_the_week.update(product_of_the_week_params)
        format.html { redirect_to @product_of_the_week, notice: 'Product of the week was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_of_the_week }
      else
        format.html { render :edit }
        format.json { render json: @product_of_the_week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_of_the_weeks/1
  # DELETE /product_of_the_weeks/1.json
  def destroy
    @product_of_the_week.destroy
    respond_to do |format|
      format.html { redirect_to product_of_the_weeks_url, notice: 'Product of the week was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_of_the_week
      @product_of_the_week = ProductOfTheWeek.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_of_the_week_params
      params.require(:product_of_the_week).permit(:name, :description, :date, :link, :published, :picture, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/co_workings_helper.rb
module CoWorkingsHelper
end

app/helpers/fundings_helper.rb
module FundingsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/product_of_the_weeks_helper.rb
module ProductOfTheWeeksHelper
end

app/views/co_workings/_form.html.erb
<%= form_for(@co_working) do |f| %>
  <% if @co_working.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@co_working.errors.count, "error") %> prohibited this co_working from being saved:</h2>

      <ul>
      <% @co_working.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/co_workings/edit.html.erb
<h1>Editing co_working</h1>

<%= render 'form' %>

<%= link_to 'Show', @co_working %> |
<%= link_to 'Back', co_workings_path %>

app/views/co_workings/index.html.erb
<% provide(:CoWorkingSpaces, 'active') %>
<% provide(:title, 'CoWorking Spaces') %>

<div class="container">

  <div class="blog-header">
    <h1 xmlns="http://www.w3.org/1999/html" class="blog-title">CoWorking Spaces</h1>
  </div>

  <hr>

  <% @co_workings.each do |co_working| %>

    <div class="row">

      <div class="col-sm-11 blog-main">
        <div class="blog-post">
          <h2 class="blog-post-title"><%= co_working.name %></h2>
          <p class="blog-post-meta"><%= co_working.updated_at.strftime("%d.%m.%Y")  %></p>
          <div class="media">
            <div class="media-left">
              <img class="media-object" src="<%= co_working.picture %>" alt="...">
            </div>
            <div class="media-body">
              <h4 class="media-heading">
                <a href="<%= co_working.url %>" target="_blank"><%= co_working.url %></a>
              </h4>
              <p>
                Standort: <%= co_working.address %><br>
              </p>
              <p>Beschreibung: <%= co_working.description %></p>
            </div>
          </div>

          <% if user_signed_in? %>
            <p>
              <%= link_to 'Show', co_working %>
              <%= link_to 'Edit', edit_co_working_path(co_working) %>
              <%= link_to 'Destroy', co_working, method: :delete, data: { confirm: 'Are you sure?' } %>
            </p>
          <% end %>

        </div><!-- /.blog-post -->
      </div><!-- /.blog-main -->
    </div><!-- /.row -->

    <hr>

  <% end %>

  <% if user_signed_in? %>
    <p><%= link_to 'New Co working', new_co_working_path %></p>
  <% end %>

</div><!-- /.container -->

app/views/co_workings/new.html.erb
<h1>New co_working</h1>

<%= render 'form' %>

<%= link_to 'Back', co_workings_path %>

app/views/co_workings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @co_working.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @co_working.address %>
</p>

<p>
  <strong>Url:</strong>
  <%= @co_working.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @co_working.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @co_working.picture %>
</p>

<%= link_to 'Edit', edit_co_working_path(@co_working) %> |
<%= link_to 'Back', co_workings_path %>

app/views/fundings/_form.html.erb
<%= form_for(@funding) do |f| %>
  <% if @funding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funding.errors.count, "error") %> prohibited this funding from being saved:</h2>

      <ul>
      <% @funding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_area :adress %>
  </div>
  <div class="field">
    <%= f.label :focus %><br>
    <%= f.text_field :focus %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :art %><br>
    <%= f.text_field :art %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fundings/edit.html.erb
<h1>Editing funding</h1>

<%= render 'form' %>

<%= link_to 'Show', @funding %> |
<%= link_to 'Back', fundings_path %>

app/views/fundings/index.html.erb
<% provide(:Funding, 'active') %>
<% provide(:title, 'Funding') %>

<div class="container">

  <div class="blog-header">
    <h1 xmlns="http://www.w3.org/1999/html" class="blog-title">Funding für Start Ups</h1>
  </div>

  <hr>

  <% @fundings.each do |funding| %>

    <div class="row">

      <div class="col-sm-11 blog-main">
        <div class="blog-post">
          <h2 class="blog-post-title"><%= funding.name %></h2>
          <p class="blog-post-meta"><%= funding.updated_at.strftime("%d.%m.%Y")  %></p>
          <div class="media">
            <div class="media-left">
              <img class="media-object" src="<%= funding.thumbnail %>" alt="...">
            </div>
            <div class="media-body">
              <h4 class="media-heading">
                <a href="<%= funding.url %>" target="_blank"><%= funding.url %></a>
              </h4>
              <p>
                Typ: <%= funding.art %><br>
                Standort: <%= funding.adress %><br>
                Fokus Gebiet: <%= funding.focus %><br>
              </p>
              <p>Beschreibung: <%= funding.description %></p>
            </div>
          </div>

          <% if user_signed_in? %>
            <p>
              <%= link_to 'Show', funding %>
              <%= link_to 'Edit', edit_funding_path(funding) %>
              <%= link_to 'Destroy', funding, method: :delete, data: { confirm: 'Are you sure?' } %>
            </p>
          <% end %>

        </div><!-- /.blog-post -->
      </div><!-- /.blog-main -->
    </div><!-- /.row -->

    <hr>

  <% end %>

  <% if user_signed_in? %>
    <p><%= link_to 'New Funding', new_funding_path %></p>
  <% end %>

</div><!-- /.container -->

app/views/fundings/new.html.erb
<h1>New funding</h1>

<%= render 'form' %>

<%= link_to 'Back', fundings_path %>

app/views/fundings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @funding.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @funding.adress %>
</p>

<p>
  <strong>Focus:</strong>
  <%= @funding.focus %>
</p>

<p>
  <strong>Url:</strong>
  <%= @funding.url %>
</p>

<p>
  <strong>Type:</strong>
  <%= @funding.art %>
</p>

<p>
  <strong>Description:</strong>
  <%= @funding.description %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @funding.thumbnail %>
</p>

<%= link_to 'Edit', edit_funding_path(@funding) %> |
<%= link_to 'Back', fundings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | StartUp Ruhrpott </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/favicon.png">

</head>
<body>
<!-- Wrap all page content here -->

  <%= render 'shared/navbar' %>

  <% flash.each do |name, msg| %>
  <div class="container">
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  </div>
  <% end %>


  <div class="container">
    <%= yield %>
  </div>

  <%= render 'shared/navbar_bottom' %>

</body>
</html>

app/views/page/Impressum.html.erb
<h1>Impressum</h1>
<hr>

<h1>Angaben gemäß § 5 TMG:</h1>
<p>Team2 Digital GmbH<br />
  Harkortstr. 66<br />
  44225 Dortmund</p>
<h2>Vertreten durch:</h2>
<p>Benjamin Spinola<br>
  Gunnar Terrahe<br />
  Patrick Sbosny</p>
<h2>Kontakt:</h2>
<table>
  <tbody>
  <tr>
    <td>Telefon:</td>
    <td>0231/33007647</td>
  </tr>
  <tr>
    <td>Telefax:</td>
    <td>0231/33005395</td>
  </tr>
  <tr>
    <td>E-Mail:</td>
    <td>info@team2digital.de</td>
  </tr>
  </tbody>
</table>
<h2>Registereintrag:</h2>
<p>Eintragung im Handelsregister.<br />
  Registergericht:Amtsgericht Dortmund<br />
  Registernummer: HRB 26732</p>
<h2>Angaben zur Berufshaftpflichtversicherung:</h2>
<p>Name und Sitz der Gesellschaft:</p>
<p>Hiscox Europe Underwriting Limited</p>
<p>Geltungsraum der Versicherung: Weltweit</p>
<h2>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</h2>
<p>Team2 Digital GmbH<br />
  Harkortstraße 66<br />
  44225 Dormtund</p>
<h2>Quellenangaben für die verwendeten Bilder und Grafiken:</h2>
<p><a href="http://www.shutterstock.com/gallery">http://www.shutterstock.com/gallery</a>-671158p1.html</p>
<p>Quelle: <em><a href="http://www.e-recht24.de/impressum-generator.html" rel="nofollow">http://www.e-recht24.de</a></em></p>
<h1>Haftungsausschluss (Disclaimer)</h1>
<p><strong>Haftung für Inhalte</strong></p>
<p>Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>
<p><strong>Haftung für Links</strong></p>
<p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>
<p><strong>Urheberrecht</strong></p>
<p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>
<p><em>Quellenangaben: <a href="http://www.e-recht24.de/muster-disclaimer.html" target="_blank" rel="nofollow">eRecht24</a></em></p>
<p>&nbsp;</p>

app/views/page/Startseite.html.erb
<% provide(:Startseite, 'active') %>
<% provide(:title, 'Startseite') %>

</div> <!-- /beendet container in application.html.erb -->

<!-- Main jumbotron for a primary marketing message or call to action -->

<div class="jumbotron">
  <div class="container">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <h1><span class="glyphicon glyphicon-signal" aria-hidden="true"></span> Start Up Ruhrpott</h1>
    <p>Die Startseite für Entrepreneure im Ruhrgebiet</p>
    <p>&nbsp;</p>
    <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p> -->
  </div>
</div>

<div class="container" style="margin-top: -90px;">
  <!-- Example row of columns -->
  <div class="row">
  
    <div class="col-md-4">
      <h2>Produkt der Woche</h2>
      <p>Du findet hier jede Woche das beste Produkt aus der internationalen Welt der Start Ups. Regelmäßig vorbeischauen lohnt sich, denn hier verbergen sich die besten Tools und Gadgets, die auch Dein StartUp boosten.</p>
      <p><%= link_to "Produkt der Woche &raquo;".html_safe, product_of_the_weeks_path(), class: "btn btn-primary" %></p>
    </div>

    <div class="col-md-4">
      <h2>Funding</h2>
      <p>Hier findest Du die wichtigsten Organisationen und Personen zum Thema Funding / Finanzierung: Venture Capitalists, Business Angels, Acceleratoren und Incubatoren für StartUps aus dem Ruhrgebiet.</p>
      <p><%= link_to "Funding &raquo;".html_safe, fundings_path(), class: "btn btn-success" %></p>
    </div>
    
    <div class="col-md-4">
      <h2>CoWorking Spaces</h2>
      <p>Kein Platz in den eigenen 4 Wänden für Dein StartUp-Team? Du suchst nach guten Kontakten zur Umsetzung Deines Produktes, Deiner Website oder App? Dann lass Dich in einem CoWorking Space blicken.</p>
      <p><%= link_to "CoWorking Spaces &raquo;".html_safe, co_workings_path(), class: "btn btn-info" %></p>
    </div>
  </div>

  <hr>


</div> <!-- /container -->
<div class="container"> <!-- /für container in application.html.erb -->

app/views/product_of_the_weeks/edit.html.erb
<h1>Editing product_of_the_week</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_of_the_week %> |
<%= link_to 'Back', product_of_the_weeks_path %>

app/views/product_of_the_weeks/index.html.erb
<% provide(:ProductOfTheWeek, 'active') %>
<% provide(:title, 'Produkt der Woche') %>

<div class="container">

  <div class="blog-header">
    <h1 class="blog-title">Start Up Produkt der Woche</h1>
  </div>

  <hr>

  <% @product_of_the_weeks.each do |product_of_the_week| %>

  <div class="row">

    <div class="col-sm-11 blog-main">
      <div class="blog-post">
        <h2 class="blog-post-title"><%= product_of_the_week.name %></h2>
        <p class="blog-post-meta"><%= product_of_the_week.date.strftime("%d.%m.%Y")  %></p>
        <div class="media">
          <div class="media-left">
              <%= image_tag(product_of_the_week.photo.url(:small), :class => "media-object") %>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <a href="<%= product_of_the_week.link %>"><%= product_of_the_week.link %></a>
            </h4>

            <%= product_of_the_week.description %>
          </div>
        </div>

        <% if user_signed_in? %>
          <p>
            <% product_of_the_week.published %>
            <%= link_to 'Show', product_of_the_week %><br>
            <%= link_to 'Edit', edit_product_of_the_week_path(product_of_the_week) %><br>
            <%= link_to 'Destroy', product_of_the_week, method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        <% end %>

      </div><!-- /.blog-post -->
    </div><!-- /.blog-main -->
  </div><!-- /.row -->

  <hr>

  <% end %>

  <% if user_signed_in? %>
    <p><%= link_to 'New Product of the week', new_product_of_the_week_path %></p>
  <% end %>
  <p>
    &nbsp;
  </p>

</div><!-- /.container -->

app/views/product_of_the_weeks/new.html.erb
<h1>New product_of_the_week</h1>

<%= render 'form' %>

<%= link_to 'Back', product_of_the_weeks_path %>

app/views/product_of_the_weeks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_of_the_week.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product_of_the_week.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @product_of_the_week.date %>
</p>

<p>
  <strong>Link:</strong>
  <%= @product_of_the_week.link %>
</p>

<p>
  <strong>Published:</strong>
  <%= @product_of_the_week.published %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @product_of_the_week.picture %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @product_of_the_week.photo.url %>
</p>

<%= link_to 'Edit', edit_product_of_the_week_path(@product_of_the_week) %> |
<%= link_to 'Back', product_of_the_weeks_path %>

app/views/shared/_navbar.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<span class='glyphicon glyphicon-signal' aria-hidden='true'></span> Start Up Ruhrpott".html_safe, page_Startseite_path(), class: "navbar-brand" %>

      <a class="navbar-brand" href=""></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= yield(:Startseite) %>"><%= link_to "Home", page_Startseite_path() %></li>
        <li class="<%= yield(:ProductOfTheWeek) %>"><%= link_to "Produkt der Woche", product_of_the_weeks_path() %></li>
        <li class="<%= yield(:Funding) %>"><%= link_to "Funding", fundings_path() %></li>
        <li class="<%= yield(:CoWorkingSpaces) %>"><%= link_to "CoWorking Spaces", co_workings_path() %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Profil', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar_bottom.erb
<nav class="navbar navbar-default navbar-fixed-bottom">

  <div class="container-fluid">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <p class="navbar-text navbar-left">&copy; Benjamin Spinola @ <a href="http://www.team2digital.de" class="navbar-link">TEAM2Digital</a></p>
      <p class="navbar-text navbar-right">&nbsp;</p>
      <p class="navbar-text navbar-right"><%= link_to 'Impressum', page_Impressum_path %></p>
      <p class="navbar-text navbar-right"><%= link_to 'Datenschutz', page_Datenschutz_path %></p>
    </div><!-- /.navbar-collapse -->


  </div>
</nav>